version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=materials
      - DB_USER=materials
      - DB_PASSWORD=materials
      - DB_HOST=db
      - DB_PORT=5432
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: materials
      POSTGRES_USER: materials
      POSTGRES_PASSWORD: materials
    ports: ["5436:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio_data:/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - INTERNAL_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
volumes:
  db_data:
  minio_data:
  frontend_node_modules:
